# Cognitive constraints
FOVEAL_SIZE = 5
WORKING_MEMORY_SIZE = 5
DEFAULT_FIXATION_DURATION = 250
DETERMINISTIC_WORD_ACTIVATION = True

# Heuristic model parameters
GAZE_DURATION_LAMDA = 0.1

# Variables
NON_WORD = "NON_WORD"
EPSILON = 1e-5
CELEX_LOG_WORD_FREQ_MIN = 0
CELEX_LOG_WORD_FREQ_MAX = 6